name: flex_facility_app
description: A gym management app for admins and clients.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.4.0
  table_calendar: ^3.0.9
  cloud_functions: ^5.5.1
  pdf: ^3.10.4
  printing: ^5.12.0
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
 
  csv: ^5.0.1

  path_provider: ^2.0.11
 

  # Firebase core packages
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  cloud_firestore: ^5.6.8

  # Local storage
  shared_preferences: ^2.2.2

  # Utility & UI
  provider: ^6.1.2
  fluttertoast: ^8.2.4
  uuid: ^4.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.63.0
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.2
  flutter_native_splash: ^2.3.5
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/flex_login/logo.png
    
flutter_native_splash:
  color: "#1C2D5E"
  image: assets/splash_logo.png
  android: true
  ios: true
  fullscreen: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  