name: flex_facility_app
description: A gym management app for admins and clients.
publish_to: 'none'
version: 1.0.0+30

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^0.13.5
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.2.2
  fluttertoast: ^8.2.4

  # Media
  video_player: ^2.8.2

  chewie: ^1.7.4  # ADD THIS - For better video controls
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  file_picker: ^10.2.0

  # UI
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.0.9
  dotted_border: ^2.1.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  cloud_functions: ^5.5.1

  # PDF & Files
  pdf: ^3.10.4
  printing: ^5.12.0
  flutter_pdfview: ^1.3.0
  share_plus: ^7.2.1
  csv: ^5.0.1
  path_provider: ^2.0.11
  open_file: ^3.5.10
  url_launcher: ^6.2.5

  # Local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  fl_chart: ^0.63.0
  percent_indicator: ^4.2.2
  square_in_app_payments: ^1.6.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.5
  webview_flutter_wkwebview: ^3.23.1
  clipboard: ^0.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/flex_login/logo.png

flutter_native_splash:
  color: "#1C2D5E"
  image: assets/splash_logo.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png